
wxapp.appid: wxbb3f0be4bf2659ca 
wxapp.mch_key: xx


server:
 port: 9999
 context-path: /cashier
spring:   
 application:
  name: 码后云外包 #同一个微服务名字一样
 #禁止mvc上传文件，使用Apache组件
 servlet.multipart.enabled: false 
 http.multipart.enabled: false
 datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: restaurant
    password: zhYKJAh6pdwSrPkJ
    url: jdbc:mysql://47.106.237.105:3306/restaurant?characterEncoding=utf-8
 druid:
    initialSize: 5 #初始化连接大小
    minIdle: 5     #最小连接池数量
    maxActive: 20  #最大连接池数量
    maxWait: 60000 #获取连接时最大等待时间，单位毫秒
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000   #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 from DUAL  #测试连接
    testWhileIdle: true                  #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
    testOnBorrow: false                  #获取连接时执行检测，建议关闭，影响性能
    testOnReturn: false                  #归还连接时执行检测，建议关闭，影响性能
    poolPreparedStatements: false        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
    maxPoolPreparedStatementPerConnectionSize: 20 #开启poolPreparedStatements后生效
    filters: stat,wall,log4j #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
    connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000' #通过connectProp
logging: 
   level:
    com.cashier.mapper: debug
mybatis: 
  mapper-locations: classpath*:com/cashier/mapper/xml/*.xml
